### PR TITLE
add script to generate bindings

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c93dd61 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c93dd61 with merge c93dd61...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/ble400/builds/235867972?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing c93dd614fdab5ad69845ea7212a8a220ba2690b0 to master...

**Pull request merged**
