### PR TITLE
UART

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 6f9d6a9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 6f9d6a9 with merge 6f9d6a9...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/ble400/builds/235898941?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 6f9d6a9a62cfc1b62100416c3ef84ed1adbbe2ea to master...

**Pull request merged**
