### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 5c7a742 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 5c7a742 with merge 5c7a742...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/ble400/builds/235497249?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3b2f05e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3b2f05e with merge 3b2f05e...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/ble400/builds/235497759?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7eccc93 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7eccc93 with merge 7eccc93...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/ble400/builds/235498444?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 19035ac has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 19035ac with merge 19035ac...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/ble400/builds/235498836?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b2a6ce0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b2a6ce0 with merge b2a6ce0...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/ble400/builds/235501030?utm_source=github_status&utm_medium=notification)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 47e0308 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 47e0308 with merge 47e0308...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/ble400/builds/235501347?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 47e03082ab7e2bbb7d6729fdfba2798984805bbc to master...

**Pull request merged**
